### ISSUE TITLE
mount: mount point jessie/rootfs-amd64.d/proc does not exist

### ISSUE THREAD

**Issue by jouhnpeng** [opencomputeproject/OpenNetworkLinux#653]
who can help me?  thanks

sudo make docker

Fetched 344 kB in 1min 17s (4457 B/s)                                                                                                                       
W: Failed to fetch http://127.0.0.1:3142/mirrors.kernel.org/debian/dists/jessie/main/binary-amd64/Packages  500  Connection failure: Connection timed out

E: Some index files failed to download. They have been ignored, or old ones used instead.
apt update failed. Exit value: 100
INFO:onlrfs:[profiler] sudo /usr/sbin/multistrap -d jessie/rootfs-amd64.d -f /tmp/tmpkqRB2M : 77.8764228821 seconds (1.29794038137 minutes)
DEBUG:onlrfs:Executing:sudo mount -t devtmpfs dev jessie/rootfs-amd64.d/dev
INFO:onlrfs:[profiler] sudo mount -t devtmpfs dev jessie/rootfs-amd64.d/dev : 0.003338098526 seconds (5.56349754333e-05 minutes)
DEBUG:onlrfs:Executing:sudo mount -t proc proc jessie/rootfs-amd64.d/proc
mount: mount point jessie/rootfs-amd64.d/proc does not exist
ERROR:onlrfs:Exception 'Could not mount proc in rfs.' in OnlRfsContext::__enter__
DEBUG:onlrfs:Executing:sudo umount -l jessie/rootfs-amd64.d/dev jessie/rootfs-amd64.d/proc
umount: jessie/rootfs-amd64.d/proc: mountpoint not found
ERROR:onlrfs:Could not unmount dev and proc
/home/sky/spsw/sps/OpenNetworkLinux/make/rfs.mk:50: recipe for target 'RFS' failed
make[3]: *** [RFS] Error 1
Traceback (most recent call last):
  File "/home/sky/spsw/sps/OpenNetworkLinux/tools/onlpm.py", line 1412, in <module>
    pm.build(p)
  File "/home/sky/spsw/sps/OpenNetworkLinux/tools/onlpm.py", line 1087, in build
    products = pg.build(dir_=dir_)
  File "/home/sky/spsw/sps/OpenNetworkLinux/tools/onlpm.py", line 690, in build
    self.gmake_locked("", 'Build')
  File "/home/sky/spsw/sps/OpenNetworkLinux/tools/onlpm.py", line 665, in gmake_locked
    ex=OnlPackageError('%s failed.' % operation))
  File "/home/sky/spsw/sps/OpenNetworkLinux/tools/onlu.py", line 126, in execute
    raise ex
onlpm.OnlPackageError: 'Build failed.'
/home/sky/spsw/sps/OpenNetworkLinux/make/pkg.mk:30: recipe for target 'pkgall' failed
make[2]: *** [pkgall] Error 1
/home/sky/spsw/sps/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/sky/spsw/sps/OpenNetworkLinux/builds/amd64'
Makefile:23: recipe for target 'amd64' failed
make: *** [amd64] Error 2

**Comment by wdqzzz** [comment]
Have you solved this issue?
