### ISSUE TITLE
master build faild

### ISSUE THREAD

**Issue by sholeksandr** [opencomputeproject/OpenNetworkLinux#669]
The current master branch build is failed.

Reproduce build flow:

```
docker/tools/onlbuilder -9
apt-cacher-ng
source setup.env
make amd64
[ ok ] Enabling additional executable binary formats: binfmt-support.
[oleksandrs@r-build-lowlevel OpenNetworkLinux_upstream_new]$ apt-cacher-ng
[oleksandrs@r-build-lowlevel OpenNetworkLinux_upstream_new]$ source setup.env
Submodule 'sm/infra' (http://github.com/floodlight/infra) registered for path 'sm/infra'
Cloning into '/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/sm/infra'...
Submodule path 'sm/infra': checked out 'd323f34967127c82bfd6c7ee28fef1e21c544d98'
Submodule 'sm/bigcode' (http://github.com/floodlight/bigcode) registered for path 'sm/bigcode'
Cloning into '/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/sm/bigcode'...
Submodule path 'sm/bigcode': checked out '2df6c06594b12de559ad3189c13d70adda68ee8e'
Submodule 'sm/build-artifacts' (http://github.com/opennetworklinux/build-artifacts) registered for path 'sm/build-artifacts'
Cloning into '/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/sm/build-artifacts'...
make amd64
```

[..]

```
NFO:onlpm:[profiler] ['sudo', 'dpkg', '-x', '/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/REPO/stretch/packages/binary-amd64/onl-platform-config-x86-64-inventec-d6254qs-r0_1.0.0_amd64.deb', 'root'] : 0.0214288234711 seconds (0.000357147057851 minutes)
INFO:onlpm:[profiler] ['sudo', 'touch', '-r', '/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/REPO/stretch/packages/binary-amd64/onl-platform-config-x86-64-inventec-d6254qs-r0_1.0.0_amd64.deb', 'root/.PKG.TIMESTAMP'] : 0.012631893158 seconds (0.000210531552633 minutes)
INFO:onlpm:[profiler] ['sudo', 'rm', 'root/.PKG.TIMESTAMP'] : 0.0130100250244 seconds (0.000216833750407 minutes)
INFO:onlpm:Rebuilding onl-platform-config-x86-64-inventec-d5254-r0:amd64... 
INFO:onlpm:Requiring prerequisite package onl-vendor-config-inventec:all...
INFO:onlpm:Requiring prerequisite package onl-vendor-config-onl:all...
INFO:onlpm:Requiring prerequisite package onl-bootd:all...
INFO:onlpm:Requiring prerequisite package onl-platform-modules-x86-64-inventec-d5254:amd64...
INFO:onlpm:Rebuilding onl-platform-modules-x86-64-inventec-d5254:amd64... 
INFO:onlpm:Requiring prerequisite package onl-kernel-4.14-lts-x86-64-all:amd64...
INFO:onlpm:Requiring prerequisite package onl-vendor-inventec-modules:amd64...
INFO:onlpm:Requiring prerequisite package onl-kernel-3.16-lts-x86-64-all:amd64...
make[5]: warning: -jN forced in submake: disabling jobserver mode.
make[6]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
/tmp/tmp.dTF3yrz1Az/inv_psoc.c: In function 'psoc_read16':
/tmp/tmp.dTF3yrz1Az/inv_psoc.c:298:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if(psoc_ipmi_read(buf, offset, 2) == 2)
     ^~
/tmp/tmp.dTF3yrz1Az/inv_psoc.c:301:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
  return value;
  ^~~~~~
/tmp/tmp.dTF3yrz1Az/inv_psoc.c: In function 'psoc_read8':
/tmp/tmp.dTF3yrz1Az/inv_psoc.c:309:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if(psoc_ipmi_read(&buf, offset, 1) == 1)
     ^~
/tmp/tmp.dTF3yrz1Az/inv_psoc.c:312:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
  return value;
  ^~~~~~
/tmp/tmp.dTF3yrz1Az/inv_vpd.c: In function 'get_swpdev_by_name':
/tmp/tmp.dTF3yrz1Az/inv_vpd.c:74:44: error: passing argument 4 of 'class_find_device' from incompatible pointer type [-Werror=incompatible-pointer-types]
                                            __swp_match);
                                            ^~~~~~~~~~~
In file included from /tmp/tmp.dTF3yrz1Az/inv_vpd.c:5:0:
./include/linux/device.h:452:23: note: expected 'int (*)(struct device *, const void *)' but argument is of type 'int (*)(struct device *, void *)'
 extern struct device *class_find_device(struct class *class,
                       ^~~~~~~~~~~~~~~~~
/tmp/tmp.dTF3yrz1Az/inv_vpd.c: In function 'store_attr_vpd':
/tmp/tmp.dTF3yrz1Az/inv_vpd.c:95:26: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     for (iLen = 0, pChar = buf_p;
                          ^
/tmp/tmp.dTF3yrz1Az/inv_vpd.c:102:47: warning: passing argument 3 of 'write_vpd_data' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  iErr = write_vpd_data( pi2c_client, iOffset, buf_p);
                                               ^~~~~
/tmp/tmp.dTF3yrz1Az/inv_vpd.c:47:5: note: expected 'char *' but argument is of type 'const char *'
 int write_vpd_data(struct i2c_client *pi2c_client, int i_offset, char *c_buf)
     ^~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:326: recipe for target '/tmp/tmp.dTF3yrz1Az/inv_vpd.o' failed
make[7]: *** [/tmp/tmp.dTF3yrz1Az/inv_vpd.o] Error 1
Makefile:1538: recipe for target '_module_/tmp/tmp.dTF3yrz1Az' failed
make[6]: *** [_module_/tmp/tmp.dTF3yrz1Az] Error 2
/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/make/kmodule.mk:28: recipe for target 'modules' failed
make[5]: *** [modules] Error 2
Traceback (most recent call last):
  File "/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/tools/onlpm.py", line 1465, in <module>
    pm.require(p, force=ops.force, build_missing=not ops.no_build_missing)
  File "/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/tools/onlpm.py", line 1123, in require
    self.build(pkg, filtered=False)
  File "/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/tools/onlpm.py", line 1083, in build
    self.require(pr, build_missing=True)
  File "/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/tools/onlpm.py", line 1123, in require
    self.build(pkg, filtered=False)
  File "/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/tools/onlpm.py", line 1087, in build
    products = pg.build(dir_=dir_)
  File "/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/tools/onlpm.py", line 690, in build
    self.gmake_locked("", 'Build')
  File "/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/tools/onlpm.py", line 665, in gmake_locked
    ex=OnlPackageError('%s failed.' % operation))
  File "/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/tools/onlu.py", line 126, in execute
    raise ex
onlpm.OnlPackageError: 'Build failed.'
/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/packages/base/any/initrds/loader/builds/Makefile:23: recipe for target 'onl-loader-initrd-amd64.cpio.gz' failed
make[4]: *** [onl-loader-initrd-amd64.cpio.gz] Error 1
ERROR:onlpm:'Build failed.'
ERROR:onlrfs:Failed to build all required packages.
/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/make/rfs.mk:50: recipe for target 'RFS' failed
make[3]: *** [RFS] Error 1
ERROR:onlpm:'Build failed.'
/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/make/pkg.mk:30: recipe for target 'pkgall' failed
make[2]: *** [pkgall] Error 1
/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/make/subdirs.mk:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/hdd/build/oleksandrs/ONL/OpenNetworkLinux_upstream_new/builds/amd64'
Makefile:23: recipe for target 'amd64' failed
make: *** [amd64] Error 2

```

**Comment by jnealtowns** [comment]
Fixed by https://github.com/opencomputeproject/OpenNetworkLinux/commit/2bdf9e83d3c08d24865afbf8d81565c94cc7b31c
