### ISSUE TITLE
build error for ONLPv2 branch

### ISSUE THREAD

**Issue by dingrui37** [opencomputeproject/OpenNetworkLinux#769]
```
root@dingrui-debian9:~/Projects/OpenNetworkLinux# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch
root@dingrui-debian9:~/Projects/OpenNetworkLinux# docker -v
Docker version 19.03.5, build 633a0ea838
```

```
root@dingrui-debian9:~/Projects/OpenNetworkLinux# export VERSION=9
root@dingrui-debian9:~/Projects/OpenNetworkLinux# make docker
Pulling opennetworklinux/builder9:1.1...
done.
[....] Starting apt-cacher-ng: apt-cacher-ngWARNING: No configuration was read from file:sfnet_mirrors
. ok 
[ ok ] Enabling additional executable binary formats: binfmt-support.
cp: cannot stat '/root/Projects/OpenNetworkLinux/sm/build-artifacts/REPO/*': No such file or directory
make -C builds/amd64
make[1]: Entering directory '/root/Projects/OpenNetworkLinux/builds/amd64'
GEN pkgall
DEBUG:onlrfs:Executing:/root/Projects/OpenNetworkLinux/tools/onlpm.py --try-arches amd64 all --skip-missing --require sysvinit-core base-files locales python apt apt-utils procps net-tools iputils-ping less sudo openssh-server iproute resolvconf vim-tiny zile nano lsof mingetty traceroute realpath rsyslog nfs-common netbase bsdmainutils ifupdown psmisc make python-cherrypy3 python-tz scapy python-pypcap snmpd snmp pciutils usbutils mtd-utils i2c-tools kmod isc-dhcp-client ntp wget ethtool localepurge telnetd python-pyinotify cpio util-linux dosfstools rssh u-boot-tools ntpdate onlp parted watchdog netplug binutils file smartmontools realpath iptables onl-faultd onlp-snmpd oom-shim python-parted python-yaml bzip2 xz-utils unzip onl-mibs openssl gdb tcpdump strace sysstat dmidecode parted smartmontools grub2 onl-upgrade hw-management onl-kernel-4.9-lts-x86-64-all-modules onl-kernel-4.14-lts-x86-64-all-modules efibootmgr gdisk onl-upgrade onlp-x86-64-inventec-d10056-r0 onl-platform-config-x86-64-inventec-d10056-r0 onlp-x86-64-inventec-d5254-r0 onl-platform-config-x86-64-inventec-d5254-r0 onlp-x86-64-inventec-d10064-r0 onl-platform-config-x86-64-inventec-d10064-r0 onlp-x86-64-inventec-d7032q28b-r0 onl-platform-config-x86-64-inventec-d7032q28b-r0 onlp-x86-64-accton-as5812-54x-r0 onl-platform-config-x86-64-accton-as5812-54x-r0 onlp-x86-64-accton-as7712-32x-r0 onl-platform-config-x86-64-accton-as7712-32x-r0 onlp-x86-64-accton-wedge100bf-32x-r0 onl-platform-config-x86-64-accton-wedge100bf-32x-r0 onlp-x86-64-delta-ag9032v1-r0 onl-platform-config-x86-64-delta-ag9032v1-r0 sysvinit-core base-files locales python apt apt-utils procps net-tools iputils-ping less sudo openssh-server iproute resolvconf vim-tiny zile nano lsof mingetty traceroute realpath rsyslog nfs-common netbase bsdmainutils ifupdown psmisc make python-cherrypy3 python-tz scapy python-pypcap snmpd snmp pciutils usbutils mtd-utils i2c-tools kmod isc-dhcp-client ntp wget ethtool localepurge telnetd python-pyinotify cpio util-linux dosfstools rssh u-boot-tools ntpdate onlp parted watchdog netplug binutils file smartmontools realpath iptables onl-faultd onlp-snmpd oom-shim python-parted python-yaml bzip2 xz-utils unzip onl-mibs openssl gdb tcpdump strace sysstat dmidecode parted smartmontools grub2 onl-upgrade hw-management onl-kernel-4.9-lts-x86-64-all-modules onl-kernel-4.14-lts-x86-64-all-modules efibootmgr gdisk onl-upgrade onlp-x86-64-inventec-d10056-r0 onl-platform-config-x86-64-inventec-d10056-r0 onlp-x86-64-inventec-d5254-r0 onl-platform-config-x86-64-inventec-d5254-r0 onlp-x86-64-inventec-d10064-r0 onl-platform-config-x86-64-inventec-d10064-r0 onlp-x86-64-inventec-d7032q28b-r0 onl-platform-config-x86-64-inventec-d7032q28b-r0 onlp-x86-64-accton-as5812-54x-r0 onl-platform-config-x86-64-accton-as5812-54x-r0 onlp-x86-64-accton-as7712-32x-r0 onl-platform-config-x86-64-accton-as7712-32x-r0 onlp-x86-64-accton-wedge100bf-32x-r0 onl-platform-config-x86-64-accton-wedge100bf-32x-r0 onlp-x86-64-delta-ag9032v1-r0 onl-platform-config-x86-64-delta-ag9032v1-r0 sysvinit-core base-files locales python apt apt-utils procps net-tools iputils-ping less sudo openssh-server iproute resolvconf vim-tiny zile nano lsof mingetty traceroute realpath rsyslog nfs-common netbase bsdmainutils ifupdown psmisc make python-cherrypy3 python-tz scapy python-pypcap snmpd snmp pciutils usbutils mtd-utils i2c-tools kmod isc-dhcp-client ntp wget ethtool localepurge telnetd python-pyinotify cpio util-linux dosfstools rssh u-boot-tools ntpdate onlp parted watchdog netplug binutils file smartmontools realpath iptables onl-faultd onlp-snmpd oom-shim python-parted python-yaml bzip2 xz-utils unzip onl-mibs openssl gdb tcpdump strace sysstat dmidecode parted smartmontools grub2 onl-upgrade hw-management onl-kernel-4.9-lts-x86-64-all-modules onl-kernel-4.14-lts-x86-64-all-modules efibootmgr gdisk onl-upgrade onlp-x86-64-inventec-d10056-r0 onl-platform-config-x86-64-inventec-d10056-r0 onlp-x86-64-inventec-d5254-r0 onl-platform-config-x86-64-inventec-d5254-r0 onlp-x86-64-inventec-d10064-r0 onl-platform-config-x86-64-inventec-d10064-r0 onlp-x86-64-inventec-d7032q28b-r0 onl-platform-config-x86-64-inventec-d7032q28b-r0 onlp-x86-64-accton-as5812-54x-r0 onl-platform-config-x86-64-accton-as5812-54x-r0 onlp-x86-64-accton-as7712-32x-r0 onl-platform-config-x86-64-accton-as7712-32x-r0 onlp-x86-64-accton-wedge100bf-32x-r0 onl-platform-config-x86-64-accton-wedge100bf-32x-r0 onlp-x86-64-delta-ag9032v1-r0 onl-platform-config-x86-64-delta-ag9032v1-r0 sysvinit-core base-files locales python apt apt-utils procps net-tools iputils-ping less sudo openssh-server iproute resolvconf vim-tiny zile nano lsof mingetty traceroute realpath rsyslog nfs-common netbase bsdmainutils ifupdown psmisc make python-cherrypy3 python-tz scapy python-pypcap snmpd snmp pciutils usbutils mtd-utils i2c-tools kmod isc-dhcp-client ntp wget ethtool localepurge telnetd python-pyinotify cpio util-linux dosfstools rssh u-boot-tools ntpdate onlp parted watchdog netplug binutils file smartmontools realpath iptables onl-faultd onlp-snmpd oom-shim python-parted python-yaml bzip2 xz-utils unzip onl-mibs openssl gdb tcpdump strace sysstat dmidecode parted smartmontools grub2 onl-upgrade hw-management onl-kernel-4.9-lts-x86-64-all-modules onl-kernel-4.14-lts-x86-64-all-modules efibootmgr gdisk onl-upgrade onlp-x86-64-inventec-d10056-r0 onl-platform-config-x86-64-inventec-d10056-r0 onlp-x86-64-inventec-d5254-r0 onl-platform-config-x86-64-inventec-d5254-r0 onlp-x86-64-inventec-d10064-r0 onl-platform-config-x86-64-inventec-d10064-r0 onlp-x86-64-inventec-d7032q28b-r0 onl-platform-config-x86-64-inventec-d7032q28b-r0 onlp-x86-64-accton-as5812-54x-r0 onl-platform-config-x86-64-accton-as5812-54x-r0 onlp-x86-64-accton-as7712-32x-r0 onl-platform-config-x86-64-accton-as7712-32x-r0 onlp-x86-64-accton-wedge100bf-32x-r0 onl-platform-config-x86-64-accton-wedge100bf-32x-r0 onlp-x86-64-delta-ag9032v1-r0 onl-platform-config-x86-64-delta-ag9032v1-r0
INFO:onlpm:Rebuilding onlp:amd64... 
make[4]: warning: -jN forced in submake: disabling jobserver mode.
Traceback (most recent call last):
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 132, in <module>
    print " ".join(mm.dependmodules(ops.dependmodules))
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 76, in dependmodules
    dp += self.dependmodules(self.modules[module]['depends'])
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 74, in dependmodules
    raise AttributeError("module %s does not exist." % module)
AttributeError: module cjson_util does not exist.
    LinkingShared[release]: libonlp-platform-defaults-module::libonlp-platform-defaults.so
Traceback (most recent call last):
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 132, in <module>
    print " ".join(mm.dependmodules(ops.dependmodules))
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 76, in dependmodules
    dp += self.dependmodules(self.modules[module]['depends'])
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 74, in dependmodules
    raise AttributeError("module %s does not exist." % module)
AttributeError: module cjson_util does not exist.
    LinkingShared[release]: libonlp-platform-module::libonlp-platform.so
Traceback (most recent call last):
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 132, in <module>
    print " ".join(mm.dependmodules(ops.dependmodules))
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 76, in dependmodules
    dp += self.dependmodules(self.modules[module]['depends'])
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 74, in dependmodules
    raise AttributeError("module %s does not exist." % module)
AttributeError: module cjson_util does not exist.
    LinkingShared[release]: libonlp-module::libonlp.so
    Compiling[ release ]: AIM::aim_valgrind.c
    Compiling[ release ]: AIM::aim_error.c
    Compiling[ release ]: AIM::aim_pvs.c
    Compiling[ release ]: AIM::aim_enums.c
    Compiling[ release ]: AIM::aim_module.c
    Compiling[ release ]: AIM::aim_log.c
    Compiling[ release ]: AIM::aim_printf.c
    Compiling[ release ]: AIM::aim_rl.c
    Compiling[ release ]: AIM::aim_string.c
    Compiling[ release ]: AIM::aim_pvs_file.c
    Compiling[ release ]: AIM::aim_datatypes.c
    Compiling[ release ]: AIM::aim_pvs_buffer.c
    Compiling[ release ]: AIM::aim_config.c
    Compiling[ release ]: AIM::aim_memory.c
    Compiling[ release ]: AIM::aim_daemon.c
    Compiling[ release ]: AIM::aim_modules_init.c
    Compiling[ release ]: AIM::aim_object.c
    Compiling[ release ]: AIM::aim_pvs_syslog.c
    Compiling[ release ]: AIM::aim_bitmap.c
    Compiling[ release ]: AIM::aim_log_handler.c
    Compiling[ release ]: AIM::aim_sparse.c
    Compiling[ release ]: AIM::aim_map.c
    Compiling[ release ]: AIM_posix::aim_time_posix.c
    Compiling[ release ]: AIM_posix::aim_thread_posix.c
    Compiling[ release ]: AIM_posix::aim_sleep_posix.c
    Compiling[ release ]: AIM_posix::aim_sem_posix.c
    Creating Library: BUILD/stretch/x86_64-linux-gnu/lib/AIM.a
    Creating Library: BUILD/stretch/x86_64-linux-gnu/lib/AIM_posix.a
    Linking[release]: onlpd-module::onlpd
BUILD/stretch/x86_64-linux-gnu/lib/AIM.a(aim_modules_init.o): In function `main':
aim_modules_init.c:(.text+0x38d): undefined reference to `onlpdump_main'
collect2: error: ld returned 1 exit status
/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/toolchains/gcc-local/bin.mk:47: recipe for target 'BUILD/stretch/x86_64-linux-gnu/bin/onlpd' failed
make[5]: *** [BUILD/stretch/x86_64-linux-gnu/bin/onlpd] Error 1
/root/Projects/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[4]: *** [all] Error 1
ERROR:onlpm:'Build failed.'
ERROR:onlrfs:Failed to build all required packages.
/root/Projects/OpenNetworkLinux/make/rfs.mk:36: recipe for target 'RFS' failed
make[3]: *** [RFS] Error 1
ERROR:onlpm:'Build failed.'
/root/Projects/OpenNetworkLinux/make/pkg.mk:30: recipe for target 'pkgall' failed
make[2]: *** [pkgall] Error 1
/root/Projects/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/root/Projects/OpenNetworkLinux/builds/amd64'
Makefile:23: recipe for target 'amd64' failed
make: *** [amd64] Error 2
Makefile:56: recipe for target 'docker' failed
make: *** [docker] Error 2

```

**Comment by ly7799** [comment]
I presume that is`docker/tool/onlbuilder` file need update 
**branch master** this file is 

```shell
   7  : ('wheezy', 'opennetworklinux/builder7:1.2'),
   8  : ('jessie',  'opennetworklinux/builder8:1.11'),
   9  : ('stretch', 'opennetworklinux/builder9:1.6' ),
   10 : ('buster',  'opennetworklinux/builder10:1.2'),
```
but your log is `Pulling opennetworklinux/builder9:1.1`

**Comment by dingrui37** [comment]
```
root@dingrui-debian9:~/Projects/OpenNetworkLinux# make docker
Pulling opennetworklinux/builder9:1.6...
done.
[....] Starting apt-cacher-ng: apt-cacher-ngWARNING: No configuration was read from file:sfnet_mirrors
. ok 
[ ok ] Enabling additional executable binary formats: binfmt-support.
cp: cannot stat '/root/Projects/OpenNetworkLinux/sm/build-artifacts/REPO/*': No such file or directory
make -C builds/amd64
make[1]: Entering directory '/root/Projects/OpenNetworkLinux/builds/amd64'
GEN pkgall
DEBUG:onlrfs:Executing:/root/Projects/OpenNetworkLinux/tools/onlpm.py --try-arches amd64 all --skip-missing --require sysvinit-core base-files locales python apt apt-utils procps net-tools iputils-ping less sudo openssh-server iproute resolvconf vim-tiny zile nano lsof mingetty traceroute realpath rsyslog nfs-common netbase bsdmainutils ifupdown psmisc make python-cherrypy3 python-tz scapy python-pypcap snmpd snmp pciutils usbutils mtd-utils i2c-tools kmod isc-dhcp-client ntp wget ethtool localepurge telnetd python-pyinotify cpio util-linux dosfstools rssh u-boot-tools ntpdate onlp parted watchdog netplug binutils file smartmontools realpath iptables onl-faultd onlp-snmpd oom-shim python-parted python-yaml bzip2 xz-utils unzip onl-mibs openssl gdb tcpdump strace sysstat dmidecode parted smartmontools grub2 onl-upgrade hw-management onl-kernel-4.9-lts-x86-64-all-modules onl-kernel-4.14-lts-x86-64-all-modules efibootmgr gdisk onl-upgrade onlp-x86-64-inventec-d10056-r0 onl-platform-config-x86-64-inventec-d10056-r0 onlp-x86-64-inventec-d5254-r0 onl-platform-config-x86-64-inventec-d5254-r0 onlp-x86-64-inventec-d10064-r0 onl-platform-config-x86-64-inventec-d10064-r0 onlp-x86-64-inventec-d7032q28b-r0 onl-platform-config-x86-64-inventec-d7032q28b-r0 onlp-x86-64-accton-as5812-54x-r0 onl-platform-config-x86-64-accton-as5812-54x-r0 onlp-x86-64-accton-as7712-32x-r0 onl-platform-config-x86-64-accton-as7712-32x-r0 onlp-x86-64-accton-wedge100bf-32x-r0 onl-platform-config-x86-64-accton-wedge100bf-32x-r0 onlp-x86-64-delta-ag9032v1-r0 onl-platform-config-x86-64-delta-ag9032v1-r0 sysvinit-core base-files locales python apt apt-utils procps net-tools iputils-ping less sudo openssh-server iproute resolvconf vim-tiny zile nano lsof mingetty traceroute realpath rsyslog nfs-common netbase bsdmainutils ifupdown psmisc make python-cherrypy3 python-tz scapy python-pypcap snmpd snmp pciutils usbutils mtd-utils i2c-tools kmod isc-dhcp-client ntp wget ethtool localepurge telnetd python-pyinotify cpio util-linux dosfstools rssh u-boot-tools ntpdate onlp parted watchdog netplug binutils file smartmontools realpath iptables onl-faultd onlp-snmpd oom-shim python-parted python-yaml bzip2 xz-utils unzip onl-mibs openssl gdb tcpdump strace sysstat dmidecode parted smartmontools grub2 onl-upgrade hw-management onl-kernel-4.9-lts-x86-64-all-modules onl-kernel-4.14-lts-x86-64-all-modules efibootmgr gdisk onl-upgrade onlp-x86-64-inventec-d10056-r0 onl-platform-config-x86-64-inventec-d10056-r0 onlp-x86-64-inventec-d5254-r0 onl-platform-config-x86-64-inventec-d5254-r0 onlp-x86-64-inventec-d10064-r0 onl-platform-config-x86-64-inventec-d10064-r0 onlp-x86-64-inventec-d7032q28b-r0 onl-platform-config-x86-64-inventec-d7032q28b-r0 onlp-x86-64-accton-as5812-54x-r0 onl-platform-config-x86-64-accton-as5812-54x-r0 onlp-x86-64-accton-as7712-32x-r0 onl-platform-config-x86-64-accton-as7712-32x-r0 onlp-x86-64-accton-wedge100bf-32x-r0 onl-platform-config-x86-64-accton-wedge100bf-32x-r0 onlp-x86-64-delta-ag9032v1-r0 onl-platform-config-x86-64-delta-ag9032v1-r0 sysvinit-core base-files locales python apt apt-utils procps net-tools iputils-ping less sudo openssh-server iproute resolvconf vim-tiny zile nano lsof mingetty traceroute realpath rsyslog nfs-common netbase bsdmainutils ifupdown psmisc make python-cherrypy3 python-tz scapy python-pypcap snmpd snmp pciutils usbutils mtd-utils i2c-tools kmod isc-dhcp-client ntp wget ethtool localepurge telnetd python-pyinotify cpio util-linux dosfstools rssh u-boot-tools ntpdate onlp parted watchdog netplug binutils file smartmontools realpath iptables onl-faultd onlp-snmpd oom-shim python-parted python-yaml bzip2 xz-utils unzip onl-mibs openssl gdb tcpdump strace sysstat dmidecode parted smartmontools grub2 onl-upgrade hw-management onl-kernel-4.9-lts-x86-64-all-modules onl-kernel-4.14-lts-x86-64-all-modules efibootmgr gdisk onl-upgrade onlp-x86-64-inventec-d10056-r0 onl-platform-config-x86-64-inventec-d10056-r0 onlp-x86-64-inventec-d5254-r0 onl-platform-config-x86-64-inventec-d5254-r0 onlp-x86-64-inventec-d10064-r0 onl-platform-config-x86-64-inventec-d10064-r0 onlp-x86-64-inventec-d7032q28b-r0 onl-platform-config-x86-64-inventec-d7032q28b-r0 onlp-x86-64-accton-as5812-54x-r0 onl-platform-config-x86-64-accton-as5812-54x-r0 onlp-x86-64-accton-as7712-32x-r0 onl-platform-config-x86-64-accton-as7712-32x-r0 onlp-x86-64-accton-wedge100bf-32x-r0 onl-platform-config-x86-64-accton-wedge100bf-32x-r0 onlp-x86-64-delta-ag9032v1-r0 onl-platform-config-x86-64-delta-ag9032v1-r0 sysvinit-core base-files locales python apt apt-utils procps net-tools iputils-ping less sudo openssh-server iproute resolvconf vim-tiny zile nano lsof mingetty traceroute realpath rsyslog nfs-common netbase bsdmainutils ifupdown psmisc make python-cherrypy3 python-tz scapy python-pypcap snmpd snmp pciutils usbutils mtd-utils i2c-tools kmod isc-dhcp-client ntp wget ethtool localepurge telnetd python-pyinotify cpio util-linux dosfstools rssh u-boot-tools ntpdate onlp parted watchdog netplug binutils file smartmontools realpath iptables onl-faultd onlp-snmpd oom-shim python-parted python-yaml bzip2 xz-utils unzip onl-mibs openssl gdb tcpdump strace sysstat dmidecode parted smartmontools grub2 onl-upgrade hw-management onl-kernel-4.9-lts-x86-64-all-modules onl-kernel-4.14-lts-x86-64-all-modules efibootmgr gdisk onl-upgrade onlp-x86-64-inventec-d10056-r0 onl-platform-config-x86-64-inventec-d10056-r0 onlp-x86-64-inventec-d5254-r0 onl-platform-config-x86-64-inventec-d5254-r0 onlp-x86-64-inventec-d10064-r0 onl-platform-config-x86-64-inventec-d10064-r0 onlp-x86-64-inventec-d7032q28b-r0 onl-platform-config-x86-64-inventec-d7032q28b-r0 onlp-x86-64-accton-as5812-54x-r0 onl-platform-config-x86-64-accton-as5812-54x-r0 onlp-x86-64-accton-as7712-32x-r0 onl-platform-config-x86-64-accton-as7712-32x-r0 onlp-x86-64-accton-wedge100bf-32x-r0 onl-platform-config-x86-64-accton-wedge100bf-32x-r0 onlp-x86-64-delta-ag9032v1-r0 onl-platform-config-x86-64-delta-ag9032v1-r0
INFO:onlpm:Rebuilding onlp:amd64... 
make[4]: warning: -jN forced in submake: disabling jobserver mode.
Traceback (most recent call last):
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 132, in <module>
    print " ".join(mm.dependmodules(ops.dependmodules))
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 76, in dependmodules
    dp += self.dependmodules(self.modules[module]['depends'])
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 74, in dependmodules
    raise AttributeError("module %s does not exist." % module)
AttributeError: module cjson_util does not exist.
Traceback (most recent call last):
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 132, in <module>
    print " ".join(mm.dependmodules(ops.dependmodules))
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 76, in dependmodules
    dp += self.dependmodules(self.modules[module]['depends'])
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 74, in dependmodules
    raise AttributeError("module %s does not exist." % module)
AttributeError: module cjson_util does not exist.
Traceback (most recent call last):
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 132, in <module>
    print " ".join(mm.dependmodules(ops.dependmodules))
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 76, in dependmodules
    dp += self.dependmodules(self.modules[module]['depends'])
  File "/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/tools/modtool.py", line 74, in dependmodules
    raise AttributeError("module %s does not exist." % module)
AttributeError: module cjson_util does not exist.
    Linking[release]: onlpd-module::onlpd
BUILD/stretch/x86_64-linux-gnu/lib/AIM.a(aim_modules_init.o): In function `main':
aim_modules_init.c:(.text+0x38d): undefined reference to `onlpdump_main'
collect2: error: ld returned 1 exit status
/root/Projects/OpenNetworkLinux/sm/infra/builder/unix/toolchains/gcc-local/bin.mk:47: recipe for target 'BUILD/stretch/x86_64-linux-gnu/bin/onlpd' failed
make[5]: *** [BUILD/stretch/x86_64-linux-gnu/bin/onlpd] Error 1
/root/Projects/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[4]: *** [all] Error 1
ERROR:onlpm:'Build failed.'
ERROR:onlrfs:Failed to build all required packages.
/root/Projects/OpenNetworkLinux/make/rfs.mk:36: recipe for target 'RFS' failed
make[3]: *** [RFS] Error 1
ERROR:onlpm:'Build failed.'
/root/Projects/OpenNetworkLinux/make/pkg.mk:30: recipe for target 'pkgall' failed
make[2]: *** [pkgall] Error 1
/root/Projects/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/root/Projects/OpenNetworkLinux/builds/amd64'
Makefile:23: recipe for target 'amd64' failed
make: *** [amd64] Error 2
Makefile:56: recipe for target 'docker' failed
make: *** [docker] Error 2

```

**Comment by ly7799** [comment]
I also found such error when Downloading the latest version of the code, but I was in the master branch, and I found that Jeffrey Townsend combined many pull branch requests, which may be one of the reasons why the previous compilation method could not compile normally.I think it's up to the author to solve the problem   @jnealtowns 

I recommend for the time being you to use [my clone](https://github.com/ly7799/OpenNetworkLinux) ,this is my most began to clone, I successfully compiled, 
or version directly back to you：

``` shell
commit 210198216ad7a724bf1c308730ff5632c5f28ef4
Author: Jeffrey Townsend <jeffrey.townsend@bigswitch.com>
Date:   Tue Jun 2 08:08:57 2020 -0700

    Add missing autobuild option for Buster.
```

**Comment by abhiranjeet** [comment]
Hi @ly7799 

Is there a stable ONL git repository where I can build Debian 9 installer for amd64 platforms ?
I am facing the exact error shared above.

Thanks !
