### ISSUE TITLE
When running  make amd64,apt update failed 

### ISSUE THREAD

**Issue by hanfeng-zz** [opencomputeproject/OpenNetworkLinux#890]
Ign:17 http://127.0.0.1:3142/apt.opennetlinux.org/debian unstable/main amd64 Packages
Ign:18 http://127.0.0.1:3142/apt.opennetlinux.org/debian unstable/main Translation-en
Ign:13 http://127.0.0.1:3142/mirrors.kernel.org/debian stretch/main all Packages
Err:14 http://127.0.0.1:3142/mirrors.kernel.org/debian stretch/main amd64 Packages
  500  Connection failure: Network is unreachable
Ign:15 http://127.0.0.1:3142/mirrors.kernel.org/debian stretch/main Translation-en
Ign:16 http://127.0.0.1:3142/apt.opennetlinux.org/debian unstable/main all Packages
Err:17 http://127.0.0.1:3142/apt.opennetlinux.org/debian unstable/main amd64 Packages
  500  Connection failure: Network is unreachable
Ign:18 http://127.0.0.1:3142/apt.opennetlinux.org/debian unstable/main Translation-en
Fetched 489 kB in 0s (6000 kB/s)
Reading package lists... Done
W: The repository 'copy:/home/zz/zz/onl/OpenNetworkLinux/REPO/stretch/packages/binary-all ./ Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'copy:/home/zz/zz/onl/OpenNetworkLinux/REPO/stretch/packages/binary-amd64 ./ Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://127.0.0.1:3142/mirrors.kernel.org/debian stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://127.0.0.1:3142/apt.opennetlinux.org/debian unstable Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://127.0.0.1:3142/mirrors.kernel.org/debian/dists/stretch/main/binary-amd64/Packages  500  Connection failure: Network is unreachable
E: Failed to fetch http://127.0.0.1:3142/apt.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages  500  Connection failure: Network is unreachable
E: Some index files failed to download. They have been ignored, or old ones used instead.
apt update failed. Exit value: 100
INFO:onlrfs:[profiler] sudo /usr/sbin/multistrap -d stretch/rootfs-amd64.d -f /tmp/tmpztL1a5 : 0.342151165009 seconds (0.00570251941681 minutes)
DEBUG:onlrfs:Executing:sudo mount -t devtmpfs dev stretch/rootfs-amd64.d/dev
INFO:onlrfs:[profiler] sudo mount -t devtmpfs dev stretch/rootfs-amd64.d/dev : 0.00913596153259 seconds (0.000152266025543 minutes)
DEBUG:onlrfs:Executing:sudo mount -t proc proc stretch/rootfs-amd64.d/proc
mount: mount point stretch/rootfs-amd64.d/proc does not exist
ERROR:onlrfs:Exception 'Could not mount proc in rfs.' in OnlRfsContext::__enter__
DEBUG:onlrfs:Executing:sudo umount -l stretch/rootfs-amd64.d/dev stretch/rootfs-amd64.d/proc
umount: stretch/rootfs-amd64.d/proc: mountpoint not found
ERROR:onlrfs:Could not unmount dev and proc
/home/zz/zz/onl/OpenNetworkLinux/make/rfs.mk:50: recipe for target 'RFS' failed
make[3]: *** [RFS] Error 1
Traceback (most recent call last):
  File "/home/zz/zz/onl/OpenNetworkLinux/tools/onlpm.py", line 1412, in <module>
    pm.build(p)
  File "/home/zz/zz/onl/OpenNetworkLinux/tools/onlpm.py", line 1087, in build
    products = pg.build(dir_=dir_)
  File "/home/zz/zz/onl/OpenNetworkLinux/tools/onlpm.py", line 690, in build
    self.gmake_locked("", 'Build')
  File "/home/zz/zz/onl/OpenNetworkLinux/tools/onlpm.py", line 665, in gmake_locked
    ex=OnlPackageError('%s failed.' % operation))
  File "/home/zz/zz/onl/OpenNetworkLinux/tools/onlu.py", line 126, in execute
    raise ex
onlpm.OnlPackageError: 'Build failed.'
/home/zz/zz/onl/OpenNetworkLinux/make/pkg.mk:30: recipe for target 'pkgall' failed
make[2]: *** [pkgall] Error 1
/home/zz/zz/onl/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/zz/zz/onl/OpenNetworkLinux/builds/amd64'
Makefile:23: recipe for target 'amd64' failed
make: *** [amd64] Error 2

root@debian9:~# uname -a
Linux debian9 4.9.0-18-amd64 #1 SMP Debian 4.9.303-1 (2022-03-07) x86_64 GNU/Linux
root@debian9:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch
root@debian9:~# docker --version
Docker version 19.03.15, build 99e3ed8919
root@debian9:~# lsof -i -n -P | grep 3142
apt-cache  7364  root    5u  IPv4 614120      0t0  TCP *:3142 (LISTEN)
apt-cache  7364  root    6u  IPv6 614121      0t0  TCP *:3142 (LISTEN)
root@debian9:~#

Thanks!

**Comment by anonymouspeople** [comment]
do you fix this problem，i have same problem。

**Comment by rishikaimal** [comment]
Have you tried using `-8`? When you run onlbuilder -8 you are running it in developer mode (for jessie). Developer mode does not use a new network namespace but instead uses the host's namespace. It give the build container full access to the local network resources.

Took reference from: https://groups.google.com/g/opennetworklinux/c/T_wnl-kZszQ/m/mYeSqk61EwAJ

**Comment by bcuhadar** [comment]
@hanfeng-zz Do you have a solution for the error you mentioned above?

W: Failed to fetch http://127.0.0.1:3142/apt.opennetlinux.org/debian/dists/unstable/main/binary-amd64/Packages  500  Connection failure: Network is unreachable

E: Some index files failed to download. They have been ignored, or old ones used instead.
apt update failed. Exit value: 100
