### ISSUE TITLE
Build Issue for fetch jessie binary-amd64 packages

### ISSUE THREAD

**Issue by jonathantsai-qci** [opencomputeproject/OpenNetworkLinux#932]
Recently ONL make docker will meet build issue as below. Any updates or workaround for this?

Ign copy: ./ InRelease
Ign copy: ./ InRelease
Ign copy: ./ Release.gpg
Ign copy: ./ Release.gpg
Ign copy: ./ Release
Ign copy: ./ Release
Get:1 copy: ./ Packages [9897 B]
Ign copy: ./ Translation-en
Get:2 copy: ./ Packages [371 kB]
Ign copy: ./ Translation-en
Ign http://127.0.0.1:3142 jessie InRelease
Ign http://127.0.0.1:3142 unstable InRelease
Ign http://127.0.0.1:3142 jessie Release.gpg
Ign http://127.0.0.1:3142 unstable Release.gpg
Ign http://127.0.0.1:3142 jessie Release
Get:3 http://127.0.0.1:3142 unstable Release [7726 B]
Get:4 http://127.0.0.1:3142 unstable/main amd64 Packages [12.4 kB]
Err http://127.0.0.1:3142 jessie/main amd64 Packages
  404  Not Found
Ign http://127.0.0.1:3142 jessie/main Translation-en
Ign http://127.0.0.1:3142 unstable/main Translation-en
Fetched 401 kB in 14s (27.6 kB/s)
W: Failed to fetch http://127.0.0.1:3142/mirrors.kernel.org/debian/dists/jessie/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
apt update failed. Exit value: 100
INFO:onlrfs:[profiler] sudo /usr/sbin/multistrap -d jessie/rootfs-amd64.d -f /tmp/tmpFcQjBN : 18.4882628918 seconds (0.308137714863 minutes)
DEBUG:onlrfs:Executing:sudo mount -t devtmpfs dev jessie/rootfs-amd64.d/dev
INFO:onlrfs:[profiler] sudo mount -t devtmpfs dev jessie/rootfs-amd64.d/dev : 0.0147058963776 seconds (0.000245098272959 minutes)
DEBUG:onlrfs:Executing:sudo mount -t proc proc jessie/rootfs-amd64.d/proc
mount: mount point jessie/rootfs-amd64.d/proc does not exist
ERROR:onlrfs:Exception 'Could not mount proc in rfs.' in OnlRfsContext::__enter__
DEBUG:onlrfs:Executing:sudo umount -l jessie/rootfs-amd64.d/dev jessie/rootfs-amd64.d/proc
umount: jessie/rootfs-amd64.d/proc: mountpoint not found
ERROR:onlrfs:Could not unmount dev and proc
/home/jonathan/project/ONL/ONL_Gerrit_4.19_pmbus_y_coretemp_m_patch_pmbus_build_1/make/rfs.mk:50: recipe for target 'RFS' failed
make[3]: *** [RFS] Error 1
Traceback (most recent call last):
  File "/home/jonathan/project/ONL/ONL_Gerrit_4.19_pmbus_y_coretemp_m_patch_pmbus_build_1/tools/onlpm.py", line 1412, in <module>
    pm.build(p)
  File "/home/jonathan/project/ONL/ONL_Gerrit_4.19_pmbus_y_coretemp_m_patch_pmbus_build_1/tools/onlpm.py", line 1087, in build
    products = pg.build(dir_=dir_)
  File "/home/jonathan/project/ONL/ONL_Gerrit_4.19_pmbus_y_coretemp_m_patch_pmbus_build_1/tools/onlpm.py", line 690, in build
    self.gmake_locked("", 'Build')
  File "/home/jonathan/project/ONL/ONL_Gerrit_4.19_pmbus_y_coretemp_m_patch_pmbus_build_1/tools/onlpm.py", line 665, in gmake_locked
    ex=OnlPackageError('%s failed.' % operation))
  File "/home/jonathan/project/ONL/ONL_Gerrit_4.19_pmbus_y_coretemp_m_patch_pmbus_build_1/tools/onlu.py", line 126, in execute
    raise ex
onlpm.OnlPackageError: 'Build failed.'
/home/jonathan/project/ONL/ONL_Gerrit_4.19_pmbus_y_coretemp_m_patch_pmbus_build_1/make/pkg.mk:30: recipe for target 'pkgall' failed
make[2]: *** [pkgall] Error 1
/home/jonathan/project/ONL/ONL_Gerrit_4.19_pmbus_y_coretemp_m_patch_pmbus_build_1/make/subdirs.mk:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/jonathan/project/ONL/ONL_Gerrit_4.19_pmbus_y_coretemp_m_patch_pmbus_build_1/builds/amd64'
Makefile:23: recipe for target 'amd64' failed
make: *** [amd64] Error 2
make: *** [Makefile:56: docker] Error 2

**Comment by jonathantsai-qci** [comment]
PR is https://github.com/opencomputeproject/OpenNetworkLinux/pull/933 and we check OK.

**Comment by jonathantsai-qci** [comment]
PR#933 is merged. Close this issue.
