### ISSUE TITLE
Facing below failure when build the ONL "ERROR:onlrfs:Exception 'Could not mount proc in rfs.' in OnlRfsContext::__enter__"

### ISSUE THREAD

**Issue by SheyamKumarVellingiri** [opencomputeproject/OpenNetworkLinux#939]
I am trying to compile the ONL using below commands.
docker/tools/onlbuilder -8
apt-cacher-ng
source setup.env
make amd64

But I am facing below failure when build the ONL. Please do the needful.

Ign http://127.0.0.1:3142/ unstable InRelease
Ign http://127.0.0.1:3142/ jessie Release.gpg
Ign http://127.0.0.1:3142/ unstable Release.gpg
Ign http://127.0.0.1:3142/ jessie Release
Get:3 http://127.0.0.1:3142/ unstable Release [7726 B]
Get:4 http://127.0.0.1:3142/ unstable/main amd64 Packages [12.4 kB]
Err http://127.0.0.1:3142/ jessie/main amd64 Packages
  404  Not Found
Ign http://127.0.0.1:3142/ jessie/main Translation-en
Ign http://127.0.0.1:3142/ unstable/main Translation-en
Fetched 304 kB in 8s (34.6 kB/s)
W: Failed to fetch http://127.0.0.1:3142/mirrors.kernel.org/debian/dists/jessie/main/binary-amd64/Packages  404  Not Found

 

E: Some index files failed to download. They have been ignored, or old ones used instead.
apt update failed. Exit value: 100
INFO:onlrfs:[profiler] sudo /usr/sbin/multistrap -d jessie/rootfs-amd64.d -f /tmp/tmpHuI1Yq : 10.0346889496 seconds (0.167244815826 minutes)
DEBUG:onlrfs:Executing:sudo mount -t devtmpfs dev jessie/rootfs-amd64.d/dev
INFO:onlrfs:[profiler] sudo mount -t devtmpfs dev jessie/rootfs-amd64.d/dev : 0.0353581905365 seconds (0.000589303175608 minutes)
DEBUG:onlrfs:Executing:sudo mount -t proc proc jessie/rootfs-amd64.d/proc
mount: mount point jessie/rootfs-amd64.d/proc does not exist
ERROR:onlrfs:Exception 'Could not mount proc in rfs.' in OnlRfsContext::__enter__
DEBUG:onlrfs:Executing:sudo umount -l jessie/rootfs-amd64.d/dev jessie/rootfs-amd64.d/proc
umount: jessie/rootfs-amd64.d/proc: mountpoint not found
ERROR:onlrfs:Could not unmount dev and proc
/home/ONL_4.14.109/OpenNetworkLinux/make/rfs.mk:50: recipe for target 'RFS' failed
make[3]: *** [RFS] Error 1
Traceback (most recent call last):
  File "/home/ONL_4.14.109/OpenNetworkLinux/tools/onlpm.py", line 1385, in <module>
    pm.build(p)
  File "/home/ONL_4.14.109/OpenNetworkLinux/tools/onlpm.py", line 1060, in build
    products = pg.build(dir_=dir_)
  File "/home/ONL_4.14.109/OpenNetworkLinux/tools/onlpm.py", line 671, in build
    self.gmake_locked("", 'Build')
  File "/home/ONL_4.14.109/OpenNetworkLinux/tools/onlpm.py", line 646, in gmake_locked
    ex=OnlPackageError('%s failed.' % operation))
  File "/home/ONL_4.14.109/OpenNetworkLinux/tools/onlu.py", line 126, in execute
    raise ex
onlpm.OnlPackageError: 'Build failed.'
/home/ONL_4.14.109/OpenNetworkLinux/make/pkg.mk:30: recipe for target 'pkgall' failed
make[2]: *** [pkgall] Error 1
/home/ONL_4.14.109/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/ONL_4.14.109/OpenNetworkLinux/builds/amd64'
Makefile:23: recipe for target 'amd64' failed
make: *** [amd64] Error 2

**Comment by dogukangulyasar** [comment]
I was struggling with this problem for several days. The following changes solved it:

https://github.com/opencomputeproject/OpenNetworkLinux/pull/933

**Comment by SheyamKumarVellingiri** [comment]
> I was struggling with this problem for several days. The following changes solved it:
> 
> #933

Thank You. I will try with this changes and let you know.

**Comment by rsys-smalagin** [comment]
For stretch we need to apply patch for onlrfs.py file, Patch looks like this. 

diff --git a/tools/onlrfs.py b/tools/onlrfs.py
index a9a4cb5d..54f3e5e6 100755
--- a/tools/onlrfs.py
+++ b/tools/onlrfs.py
@@ -302,7 +302,7 @@ class OnlRfsBuilder(object):

     DEFAULTS = dict(
         DEBIAN_SUITE='wheezy',
-        DEBIAN_MIRROR='mirrors.kernel.org/debian/',
+        DEBIAN_MIRROR='archive.debian.org/debian/',
         APT_CACHE='127.0.0.1:3142/'
         )
